# Site settings
title: Viatge al País dels Somnis
email: lauraponslloret@gmail.com
description: "diari d'una vida, i més!"
baseurl: ""
url: "http://napbuf.es"
twitter_username: none
github_username:  napbuf
facebook_username:  Laura Pons Lloret

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]